import Head from 'next/head'
import Image from 'next/image'
import Button from 'react-bootstrap/Button';
import Login from '../components/Login'

export default function Home() {
  return (
    <div>
      <Head>
        <title>AiTuting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Login />
      </main>

      <footer>
      </footer>
    </div>
  )
}
